site_name: bib2x
site_url: https://github.com/dkrajzew/bib2x
site_description: A BibTex parser and converter.
site_author: Daniel Krajzewicz
docs_dir: ./mkdocs

repo_url: https://github.com/dkrajzew/bib2x.git
edit_uri: ""

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
    palette:
        primary: light green
        
nav:
    - Home: index.md
    - Installation: install.md
    - Usage: 
        - Command Line: cmd.md
    - Links: links.md
    - API:
        - bib2x: api_bib2x.md
        - TeXfile: api_texfile.md
        - TeXhandler: api_texhandler.md
        - TeXhandler.JSON: api_texhandler_json.md
        - TeXhandler.Memory: api_texhandler_memory.md
    - Developer Docs:
        - How To Release: release.md
    - ChangeLog: changes.md
    - License (BSD): license.md
    - Legal: legal.md

markdown_extensions:
    - admonition
    - sane_lists
  
copyright: "&copy; Copyright 2011&ndash;2014, 2023 Daniel Krajzewicz."

use_directory_urls: false

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                paths: [../bib2x]
                options:
                    filters: [""]
                    show_source: False
                    docstring_style: "google"